### ISSUE TITLE
Line Length

### ISSUE THREAD

**Issue by jaredkove** [langleyfoxall/technologies#63]
Pulled into a new issue from #62 for a more civilised discussion.
==========

if you have an element that looks like the following:
```
<a 
        style="display:inline-block;" alt="Big A"
/>
```
The spacing should instead look like
```
<a style="display:inline-block;" alt="Big A" />
```
--
However there is a caveat for this, if your line is exceeding X chars, then you should start a new line for that element and indent on that new line.

**Comment by dextermb** [comment]
If everything can fit onto a single line then the second example should be what is used. But if things are moved onto multiple lines, be it because of one attribute or not then I think it should follow this structure:

```
<img
    id="<an id>"
    class="<a class>"
    src="<a src>"
/>
```
 
Rather than:
```
<img id="<an id>"
    class="<a class>"
    src="<a src>"
/>
```

It's a subtle difference but I think the first attribute should be below the tag itself, as seen in most React codebases. The code where the first example dirived from was from yourfreebet-laravel.

```html
<a 
  style="display:inline-block;" alt="Colossus Bets Sponsor"
  href="https://www.colossusbets.com/pools/list/sports?registration=true&cb_ref_code=YOURFREEBET&utm_source=YFB&utm_medium=Website&utm_campaign=Header&utm_content=Header"
></a>
```

**Comment by wheatleyjj** [comment]
Let's get this actioned and added then.

**Comment by AlexCatch** [comment]
We need a maximum line length to ensure that there is a cutoff for when we start to place each attribute on a new line.

The standard for tools like Prettier (which me and Ash use in a project to enforce our style guide) uses 80 characters as the limit because it's quite common for developers to work with multiple panes these days & also because a single expression should never typically go over 80.

**Comment by dextermb** [comment]
> We need a maximum line length to ensure that there is a cutoff for when we start to place each attribute on a new line.
> 
> The standard for tools like Prettier (which me and Ash use in a project to enforce our style guide) uses 80 characters as the limit because it's quite common for developers to work with multiple panes these days & also because a single expression should never typically go over 80.

I believe PHPStorm's default hard wrap is `120` which seems like a decent number. The main culprit for going over the line length seems to be when people are scared to knock array elements onto new lines, for example, or listing relationships in `load` or `with` in Laravel.

**Comment by AlexCatch** [comment]
@dextermb I'm happy with 120.

**Comment by DivineOmega** [comment]
Agree with line formatting suggestions and max line length of 120.

**Comment by ash123456789** [comment]
120 all the way.

**Comment by DivineOmega** [comment]
Looks like we have consensus here on a 120 character line length, and formatting HTML in the following manner for tags that span multiple line.

```html
<img
    id="<an id>"
    class="<a class>"
    src="<a src>"
/>
```
