### ISSUE TITLE
Spaces in string concatenation

### ISSUE THREAD

**Issue by ash123456789** [langleyfoxall/technologies#74]
### What you would like to change/add

Since we have started to adopt StyleCI I have been working on creating a standard configuration for our Laravel projects. One thing I noticed is that StyleCI likes to remove spaces in string concatenation and, as far as I am aware, we have no internal style guide for it and PSR has no defined standard for it either.

We can either enforce there to be spaces or enforce no spaces.

### Why you would like to change/add this

I personally think that we should have spaces since it improves readability, especially if there are multiple variables.

### Examples

**concat_without_spaces**
```php
return $this->first_name . ' ' . $this->last_name;
```
would then become:
```php
return $this->first_name.' '.$this->last_name;
```

**concat_with_spaces**
```php
return $this->first_name.' '.$this->last_name;
```
would then become:
```php
return $this->first_name . ' ' . $this->last_name;
```

### Checklist
- [x] I have checked that this is not a duplicate issue.

👍 for with spaces.
👎 for without spaces.

**Comment by dextermb** [comment]
> **concat_with_spaces**
> 
> ```
> return $this->first_name.' '.$this->last_name;
> ```
> 
> would then become:
> 
> ```
> return $this->first_name . ' ' . $this->last_name;
> ```

This is probably the easiest to read. The only issue would be that strings get very long. If you're appending a decent amount of things together it's probably tidier to use `explode` on an array or something (not quicker though).

**Comment by wheatleyjj** [comment]
Thanks for making the issue, @ash123456789.

As I mentioned to you my personal preference is to have no spaces in this instance - so I'll be thumbsing you down, but we will see 👍

**Comment by ash123456789** [comment]
👍 for with spaces.
👎 for without spaces.

**Comment by DivineOmega** [comment]
I'm with @wheatleyjj here. I prefer no spaces.

**Comment by AlexCatch** [comment]
I prefer no spaces also, I think unnecessary and doesn't make it anymore readable imo

**Comment by JamesLF** [comment]
Much prefer with spaces:
1. Much easier to read because more whitespace always makes things easier to read, same reason separate arguments in a method have spaces after every comma.
2. When elements have no space between them, it suggests the two items have an already existing connection between them. When you add numbers, you don't do `1234+23342`, you do `1234 + 23342` because they are two separate items. The space helps underline you about to combine two items.
3. Less confusion with every other sensible language such as JavaScript, C# and so on, where `x.y` means _y, an element of x_, but PHP decided to use `->` for that instead.

**Comment by AlexCatch** [comment]
I say we leave this open for a few more days for people to make up their mind.

Let's say this Friday.
